{
   "hostfile": "logs/llama-7B-mat/hostfile",
   "tensorboard-dir": "logs/llama-7B-mat/tensorboard",
   "save": "logs/llama-7B-mat/checkpoints",
   "load": "logs/llama-7B-mat/checkpoints",

   "data-path": "/lustre/orion/stf218/scratch/junqi/frontier/data/mat/material_text_document",
   "vocab-file": "/lustre/orion/stf218/scratch/junqi/frontier/data/mat/material_vocab.json",
   "tokenizer_type": "HFTokenizer",
 
   "train_micro_batch_size_per_gpu": 8,
   #aws-rccl workaround
   "num_workers": 0, 


  #"pipe-parallel-size": 1,
  "model-parallel-size": 1,
  "make_vocab_size_divisible_by": 1,

  # model settings
  "num-layers": 32,
  "hidden-size": 4096,
  "num-attention-heads": 32,
  "seq-length": 2048,
  "max-position-embeddings": 2048,
  "pos-emb": "rotary",
  "rotary-pct": 1,
  "no-weight-tying": true,
  "gpt-j-residual": false,
  "output-layer-parallelism": "column",
  "norm": "rmsnorm",
  "rms_norm_epsilon": 1.0e-6,

  "scaled-upper-triang-masked-softmax-fusion": true,
  "bias-gelu-fusion": true,
  "use_bias_in_norms": false,
  "use_bias_in_attn_linear": false,
  "mlp_type": "llama",
  "activation": "silu",

   "optimizer": {
     "type": "LAMB",
     "params": {
       "lr": 0.006,
       "betas": [0.9, 0.999],
       "eps": 1.0e-8,
     }
   },
   "min_lr": 0.0006,

   "zero_optimization": {
    "stage": 1,
    "allgather_partitions": True,
    "allgather_bucket_size": 500000000,
    "overlap_comm": True,
    "reduce_scatter": True,
    "reduce_bucket_size": 500000000,
    "contiguous_gradients": True,
    "cpu_offload": False
  },

   # data settings
   "data-impl": "mmap",
   "split": "949,50,1",

   # activation checkpointing
   "checkpoint-activations": true,
   "checkpoint-num-layers": 1,
   "partition-activations": true,
   "synchronize-each-layer": true,

   # regularization
   "gradient_clipping": 1.0,
   "weight-decay": 0.01,
   "hidden-dropout": 0,
   "attention-dropout": 0,

   # precision settings
   "fp16": {
     #"fp16": true,
     "type": "bfloat16",
     "enabled": true,
     "loss_scale": 0,
     "loss_scale_window": 1000,
     "hysteresis": 2,
     "min_loss_scale": 1
   },

   # misc. training settings
   "train-iters": 3700,
   "lr-decay-iters": 3700,
   "distributed-backend": "nccl",
   "lr-decay-style": "cosine",
   "warmup": 0.01,
   "checkpoint-factor": 100,
   "eval-interval": 100,
   "eval-iters": 10,

   # logging
   "log-interval": 20,
   "steps_per_print": 10,
   "keep-last-n-checkpoints": 100,
   "wall_clock_breakdown": true,

}
